env:
  node: true
  es6: true
  mocha: true
parserOptions:
  ecmaVersion: 8
extends:
  - eslint:recommended
  - google
rules:
  max-len: off
  no-console: error
  require-jsdoc: off
  valid-jsdoc: off
